# Generated by Django 4.1.3 on 2022-11-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0001_initial'),
        ('myapp1', '0003_salesorder_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp3.account'),
        ),
    ]
